login_check:
  path: /login_check
  controller: App\Controller\AuthController::getToken
register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
